# IRONVOW — one image, two entry points.
#
# The API and the web app share a workspace, a lockfile and most of their
# dependencies, so building them twice would install pnpm's whole store twice
# for no gain. The `api` and `web` stages differ only in what they run.
#
# Built and run by docker-compose.yml. See the Deploy section of README.md.

# Debian, not Alpine. Prisma's query engine needs glibc and OpenSSL 3, and on
# node:22-alpine it fails to load at all — `prisma migrate deploy` died with
# "could not parse schema engine response" on every boot, so the API never
# came up once, and the first deployment spent an hour showing the symptoms
# of a missing API instead of the cause.
FROM node:22-bookworm-slim AS base
RUN apt-get update \
 && apt-get install -y --no-install-recommends openssl ca-certificates \
 && rm -rf /var/lib/apt/lists/*
RUN corepack enable
WORKDIR /app

# ---------------------------------------------------------------- install ---
# The manifests alone first, so a change to a source file does not re-run the
# install. Every workspace package has to be listed: pnpm reads them all before
# it will resolve `workspace:*`.
FROM base AS deps
COPY package.json pnpm-lock.yaml pnpm-workspace.yaml .npmrc turbo.json ./
COPY packages/config/package.json packages/config/
COPY packages/types/package.json packages/types/
COPY packages/sim/package.json packages/sim/
COPY apps/api/package.json apps/api/
COPY apps/web/package.json apps/web/
RUN pnpm install --frozen-lockfile

# ------------------------------------------------------------------ build ---
FROM deps AS build
COPY . .
# Prisma's client is generated by a postinstall that pnpm 10 blocks by default,
# so it is run explicitly rather than left to chance.
RUN pnpm --filter @ironvow/api exec prisma generate
# Two different addresses for the same API, and both are baked in here.
# NEXT_PUBLIC_API_URL is inlined into the browser bundle, so it is a path the
# phone can use; API_PROXY_URL is compiled into the rewrite table, so it is the
# address the Next server can reach. See apps/web/next.config.mjs.
ARG NEXT_PUBLIC_API_URL=/api
ARG API_PROXY_URL=http://api:4000
ENV NEXT_PUBLIC_API_URL=$NEXT_PUBLIC_API_URL
ENV API_PROXY_URL=$API_PROXY_URL
RUN pnpm build

# ------------------------------------------------------------------- runs ---
FROM build AS api
ENV NODE_ENV=production
EXPOSE 4000
# Migrations run on boot. One command, and the schema is never behind the code
# that expects it.
CMD ["sh", "-c", "pnpm --filter @ironvow/api exec prisma migrate deploy && node apps/api/dist/server.js"]

FROM build AS worker
ENV NODE_ENV=production
CMD ["node", "apps/api/dist/worker.js"]

FROM build AS web
ENV NODE_ENV=production
EXPOSE 3000
CMD ["pnpm", "--filter", "@ironvow/web", "start"]
