-- AlterTable
ALTER TABLE "Player" ADD COLUMN     "claimedQuests" TEXT[] DEFAULT ARRAY[]::TEXT[],
ADD COLUMN     "collected" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "isGuest" BOOLEAN NOT NULL DEFAULT false,
ADD COLUMN     "raids" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "threeStars" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "trainedTotal" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN     "wins" INTEGER NOT NULL DEFAULT 0;
